"""
Report Generator - Creates match analysis reports.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Optional

from core import FitAnalysis, MatchResult, TailoredContent


class ReportGenerator:
    """Generates analysis reports in various formats."""
    
    def __init__(self, config):
        self.config = config
    
    def generate_markdown(
        self,
        analysis: FitAnalysis,
        matches: MatchResult,
        tailored: TailoredContent,
        output_path: Path
    ) -> None:
        """Generate a markdown analysis report."""
        
        report = f"""# Resume Match Analysis
*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

---

## Overall Fit Score: {analysis.overall_score:.0%}

| Category | Score |
|----------|-------|
"""
        
        for category, score in analysis.score_breakdown.items():
            report += f"| {category.replace('_', ' ').title()} | {score:.0%} |\n"
        
        report += f"""
### Keyword Coverage
- **Matched:** {analysis.keywords_matched} / {analysis.keywords_total}
- **Coverage:** {analysis.keywords_matched / analysis.keywords_total * 100:.0f}%

---

## Seniority Assessment
**Fit:** {analysis.seniority_fit.upper()}

"""
        if analysis.salary_assessment:
            report += f"**Salary Expectation:** {analysis.salary_assessment}\n\n"
        
        report += """---

## Strengths
"""
        for strength in analysis.strengths:
            report += f"✅ {strength}\n\n"
        
        report += """
---

## Gaps to Address
"""
        for gap in analysis.gaps:
            report += f"⚠️ {gap}\n\n"
        
        if analysis.red_flags:
            report += """
---

## Potential Concerns
"""
            for flag in analysis.red_flags:
                report += f"🚩 {flag}\n\n"
        
        report += """
---

## Interview Talking Points
"""
        for i, point in enumerate(analysis.talking_points, 1):
            report += f"{i}. {point}\n\n"
        
        report += """
---

## Changes Made to Resume

"""
        report += f"- **Bullets rewritten:** {tailored.bullets_rewritten}\n"
        report += f"- **Roles reordered:** {tailored.bullets_reordered}\n"
        report += f"- **Keywords added:** {', '.join(tailored.keywords_added) if tailored.keywords_added else 'None'}\n"
        
        report += """
---

## Top Matching Experience

| Score | Bullet | Matched To |
|-------|--------|------------|
"""
        
        top_matches = sorted(
            matches.bullet_matches, 
            key=lambda m: m.score, 
            reverse=True
        )[:10]
        
        for match in top_matches:
            bullet_preview = match.original_bullet[:60] + "..." if len(match.original_bullet) > 60 else match.original_bullet
            requirements = ", ".join(match.matched_requirements[:2]) if match.matched_requirements else "General fit"
            report += f"| {match.score:.0%} | {bullet_preview} | {requirements} |\n"
        
        report += """
---

## Missing Keywords

"""
        if matches.missing_keywords:
            for keyword in matches.missing_keywords[:10]:
                suggestion = matches.keyword_suggestions.get(keyword, "Consider adding to relevant experience")
                report += f"- **{keyword}**: {suggestion}\n"
        else:
            report += "*All key terms covered!*\n"
        
        report += """
---

*This analysis was generated by Resume Tailor. Good luck with your application!*
"""
        
        # Write report
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(report)
    
    def generate_json(
        self,
        analysis: FitAnalysis,
        matches: MatchResult,
        tailored: TailoredContent,
        output_path: Path
    ) -> None:
        """Generate a JSON analysis report."""
        
        report = {
            "generated_at": datetime.now().isoformat(),
            "overall_score": analysis.overall_score,
            "keyword_coverage": {
                "matched": analysis.keywords_matched,
                "total": analysis.keywords_total,
                "percentage": analysis.keywords_matched / analysis.keywords_total if analysis.keywords_total else 0
            },
            "score_breakdown": analysis.score_breakdown,
            "seniority_fit": analysis.seniority_fit,
            "salary_assessment": analysis.salary_assessment,
            "strengths": analysis.strengths,
            "gaps": analysis.gaps,
            "red_flags": analysis.red_flags,
            "talking_points": analysis.talking_points,
            "changes_made": {
                "bullets_rewritten": tailored.bullets_rewritten,
                "bullets_reordered": tailored.bullets_reordered,
                "keywords_added": tailored.keywords_added
            },
            "top_matches": [
                {
                    "bullet": m.original_bullet,
                    "score": m.score,
                    "matched_requirements": m.matched_requirements,
                    "matched_keywords": m.matched_keywords,
                    "suggested_rewrite": m.suggested_rewrite
                }
                for m in sorted(matches.bullet_matches, key=lambda x: x.score, reverse=True)[:10]
            ],
            "missing_keywords": matches.missing_keywords,
            "keyword_suggestions": matches.keyword_suggestions
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)
    
    def generate_console_summary(
        self,
        analysis: FitAnalysis,
        matches: MatchResult
    ) -> str:
        """Generate a brief console-friendly summary."""
        
        lines = [
            f"Match Score: {analysis.overall_score:.0%}",
            f"Keywords: {analysis.keywords_matched}/{analysis.keywords_total}",
            f"Seniority: {analysis.seniority_fit}",
            "",
            "Top Strengths:",
        ]
        
        for strength in analysis.strengths[:3]:
            lines.append(f"  ✅ {strength}")
        
        lines.append("")
        lines.append("Key Gaps:")
        
        for gap in analysis.gaps[:3]:
            lines.append(f"  ⚠️ {gap}")
        
        return "\n".join(lines)
